name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clear Old Cache and Setup New
      uses: actions/cache@v4
      with:
        path: |
          .buildozer
          ~/.buildozer
        key: ${{ runner.os }}-buildozer-v3-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-v3-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            python3-dev \
            ffmpeg \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            libportmidi-dev \
            libswscale-dev \
            libavformat-dev \
            libavcodec-dev \
            zlib1g-dev \
            zip \
            unzip \
            autoconf \
            libtool \
            pkg-config \
            libffi-dev \
            libssl-dev

        pip install --upgrade pip
        pip install "cython<3.0"
        pip install "kivy[base]"
        pip install git+https://github.com/kivy/buildozer.git@master

    - name: Build with Buildozer
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
